server:
  port: 7777
spring:
  datasource:
    url: jdbc:mysql://1.12.237.207:3306/sg_blog?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB
  redis:
    host: 1.12.237.207
    port: 6379
    password: 1234


mybatis-plus:
  configuration:
  # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto

minio:
  endpointUrl: http://1.12.237.207:9001
  accessKey: admin
  secreKey: admin123456
  bucketName: qs-blog
